blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix: /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
